import Head from "next/head";
import styles from "../styles/About.module.css";
import Path from "../components/Path";
import { Container, Image } from "react-bootstrap";
import { getAllEmployee } from "../lib/api";
import Img from "next/image";
import BlockContent from "@sanity/block-content-to-react";

export default function Aboutus({ employee }) {
    // const serializers = {
    //     types: {
    //         code: (props) => (
    //             <pre data-language={props.node.language}>
    //                 <code>{props.node.code}</code>
    //             </pre>
    //         ),
    //     },
    // };
    const myLoader = ({ src }) => {
        return `${src}`;
    };
    return (
        <>
            <Head>
                <title>Naadam Festival</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="https://cdn.sanity.io/images/aj69bwet/production/87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png?w=1000&h=1000&fit=max"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link rel="canonical" href="http://naadamfest.com/aboutus" />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>
            <main>
                <div>
                    <Path name="About Us" />
                    <Container>
                        <div className={styles.main}>
                            <h1>WHO WE ARE</h1>
                            <p>
                                Welcome to the Jargal Expedition LLC.
                                <br />
                                It is a fully licensed and locally operated
                                Mongolian company. We are serving to the needs
                                of the discerning traveller who wants the
                                benefits of a tour where all the hard work is
                                done but without the hassle of being lost in a
                                crowd, as with the larger companies. We&apos;ve
                                been around since 2010 and we have set up
                                holiday destinations in main attractive areas in
                                our country. For years we&apos;ve been arranging
                                distinctive adventure holidays throughout
                                Mongolia. Each is personally designed to suit
                                you to perfection.
                                {/*<br /> It is a fully licensed and locally*/}
                                {/*operated Mongolian tour operator company. We are*/}
                                {/*serving to the needs of the discerning traveller*/}
                                {/*who wants the benefits of a tour where all the*/}
                                {/*hard work is done but without the hassle of*/}
                                {/*being lost in a crowd, as with the larger*/}
                                {/*companies. We&apos;ve been around since 2010 and*/}
                                {/*we have set up holiday destinations in main*/}
                                {/*attractive areas in our country. For years*/}
                                {/*we&apos;ve been arranging distinctive adventure*/}
                                {/*holidays throughout Mongolia. Each is personally*/}
                                {/*designed to suit you to perfection.*/}
                            </p>
                            {/*<h3>*/}
                            {/*    They are your key to releasing the wonders of*/}
                            {/*    adventure travel in Mongolia.*/}
                            {/*</h3>*/}
                        </div>
                        {/*{employee.map((emp, index) => (*/}
                        {/*    <>*/}
                        {/*        <div className={styles.employee} key={index}>*/}
                        {/*            <div className={styles.image}>*/}
                        {/*                <Img*/}
                        {/*                    src={emp.image}*/}
                        {/*                    layout="responsive"*/}
                        {/*                    width={400}*/}
                        {/*                    height={300}*/}
                        {/*                    alt="employee image"*/}
                        {/*                    objectFit="cover"*/}
                        {/*                />*/}
                        {/*            </div>*/}

                        {/*            <div className={styles.info}>*/}
                        {/*                <h1>{emp.name}</h1>*/}
                        {/*                <BlockContent blocks={emp.bio} />*/}
                        {/*            </div>*/}
                        {/*        </div>*/}
                        {/*    </>*/}
                        {/*))}*/}

                        <div className={styles.our_ethos}>
                            <h1>OUR ETHOS, BELIEFS, PRINCIPLES</h1>
                            <p>
                                <span>DISCOVER OFF THE BEATEN PATH</span>
                                <br />
                                Our vibrant tradition, culture, lifestyle and
                                diverse natural environments will energize your
                                senses and satisfy your most adventurous travel
                                dreams.
                            </p>
                            <p>
                                <span>HAVE AUTHENTIC EXPERIENCES</span>
                                <br /> Communicate with local people about why
                                and what and how. As the doors open up and you
                                are more comfortable with them and they with you
                                they will start to ask you questions as well.
                                This is a beauty of cultural exchange for all
                                involved. This bond of cultural learning is
                                unique and a fun way to travel getting to know
                                the local people. It requires a willingness to
                                leave some of our own cultural norms in our
                                luggage during the trip in order to fully dive
                                in. It’s genuine. The rewards are incredible.
                            </p>
                            <p>
                                <span>
                                    TRAVEL WITHOUT A HITCH & FEEL GOOD ABOUT
                                    TRAVEL
                                </span>
                                <br /> Your trip will be organised to your
                                expectation and in some cases exceeded your
                                expectation. As usual, with great efforts of our
                                dedicated team, everything goes without a hitch
                                and you are able to enjoy throughout your travel
                                with us.
                            </p>
                        </div>
                        <div className={styles.our_ethos}>
                            <h1>Why Jargal Expedition</h1>
                            <p>
                                <span>WE ARE LOCALS</span>
                                <br />
                                We are truly enthusiastic about representing you
                                the many features of our amazing country. We
                                believe ourselves as generation of nomadic
                                people and proud so that as imperatively, we are
                                honour of operating adventure tours for guests
                                and giving them opportunity to experience about
                                our culture and tradition through our selected
                                discovery destinations in our country.
                            </p>
                            <p>
                                <span>GUARANTEED ROUTE & REAL ADVENTURE</span>
                                <br />
                                We don&apost offer overpriced luxury but tightly
                                scripted both guaranteed route and real
                                adventure. With assistance of our dedicated team
                                and comfortable accommodation arrangement in the
                                backcountry, we will provide you an authentic
                                and real-life adventure in Mongolia.
                            </p>
                            <p>
                                <span>PERSONAL SERVICE</span>
                                <br />
                                Our personal service begins with your first
                                enquiry and extends through your whole trip. For
                                years we&apos;ve been arranging distinctive
                                adventure holidays throughout Mongolia. Each is
                                personally designed to suit you to perfection.
                                We keenly understand that your vacation is the
                                most valuable time of the year and we are
                                committed to make it the most memorable time of
                                your life.
                            </p>
                        </div>
                    </Container>
                </div>
            </main>
        </>
    );
}

export const getServerSideProps = async () => {
    const employee = await getAllEmployee();
    return {
        props: {
            employee,
        },
    };
};
