import Head from "next/head";
import Path from "../components/Path";
import styles from "../styles/About.module.css";
import { Container } from "react-bootstrap";

export default function Booking() {
    return (
        <>
            <Head>
                <title>Naadam Festival</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link
                    rel="canonical"
                    href="http://naadamfest.com/bookingtermsandconditions"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>

            <div>
                <Path name="Booking Terms And Conditions" />
                <Container>
                    <div className={styles.main}>
                        <h1>GENERAL CONDITIONS</h1>
                        <p>
                            These terms will apply to your contract with Jargal
                            Expedition LLC for all adventure tours, the company
                            registered in Mongolia and registration number 649-
                            7969. Please read them carefully before you book.
                        </p>
                        <h3>1. BEFORE YOU BOOK</h3>
                        <h3>1.1 PLANNING YOUR HOLIDAY</h3>
                        <p>
                            Jargal Expedition aims to provide exactly the right
                            holiday to suit your requirements. Jargal Expedition
                            is fully responsible for adventure holidays and
                            horse riding engagements.{" "}
                        </p>
                        <h3>1.2 DATA PROTECTION</h3>
                        <p>
                            {" "}
                            In order to process your booking and ensure that
                            your travel arrangements run and meet your
                            requirements, we need to use the information you
                            provide such as your name and address, and any
                            special needs/dietary requirements. You acknowledge
                            to have read and agree to this privacy policy. We
                            take full responsibility for ensuring that proper
                            security measures are in place to protect your
                            information. We must pass the information on to the
                            relevant suppliers of your travel arrangements such
                            as domestic airlines and hotels and so on. We will
                            not pass any information on to any person not
                            responsible for part of your travel arrangements.
                            Please read our Privacy Policy. You acknowledge to
                            have read and agree to this privacy policy.
                        </p>
                        <h3>
                            2. BOOKING AND PAYING FOR YOUR HOLIDAY IN MONGOLIA
                        </h3>
                        <h3>2.1 MAKING A BOOKING</h3>
                        <p>
                            After discussing your requirements, we will send you
                            a detailed itinerary setting out the transport,
                            accommodation, meals and other services which will
                            be provided as part of your holiday and the cost per
                            person. You should check that these meet with your
                            approval and contact us as soon as possible to make
                            any changes. Once the itinerary and price has been
                            agreed in principle you can book the holiday by
                            completing our booking form and returning it to us
                            with a deposit 15% of the holiday price per person,
                            or such other sum as we may notify to you at the
                            time of booking. This amount is non-refundable, and
                            is deducted from the total amount due for your
                            chosen trip. We are not responsible for refunding
                            bank charges on any payments by card or bank
                            transfer. Please note the current charge on the card
                            payment is 4%. Once you have confirmed your booking
                            the price of your tour is guaranteed and will not be
                            subject to any surcharge. After receiving your
                            booking form and the deposit, we will send you a
                            confirmation invoice of your booking along with
                            details for the payment of the balance and other
                            related documents. Your booking will not be accepted
                            and no contract authorized until the deposit is
                            received. When you make a booking you are confirming
                            that you understand and have accepted on behalf of
                            yourself and all members of your party our booking
                            conditions.{" "}
                        </p>
                        <h3>2.2 PAYING FOR OR CANCELLING YOUR HOLIDAY</h3>
                        <p>
                            {" "}
                            After your booking has been taken and a deposit
                            received, a confirmation invoice will be sent to you
                            detailing the total cost due. Full payment is due to
                            reach us not less than 30 days before departure. If
                            you do not pay in full 30 days before departure, we
                            reserve the right to cancel your booking, and
                            forfeit the deposit by way of cancellation charge.
                            If you make a booking within 30 days of your
                            departure date then you must pay the full cost of
                            the holiday at the booking stage. The balance of the
                            fees for the tour is due thirty days prior to
                            departure and we have not received payment by the
                            due date we will regard the booking as cancelled. As
                            a choice, for a late booking, if you have chosen
                            travelling with us, you must pay the deposit at the
                            time of reservation and must pay the outstanding
                            balance at least 3 weeks prior to the departure date
                            of your trip. If you register within 3 weeks of
                            departure, the full cost should be paid at the time
                            of registration. All payments can be made by
                            international bank transfers or by credit cards
                            (Visa, Master) payment. By Credit Card: It is
                            possible to pay /the deposit only/ on-line here. By
                            bank transfer: please transfer 30 days prior your
                            arrival day the final amount via SWIFT to our bank
                            /Bank details will be sent on your request/. Then
                            either scan and email your transfer receipt to
                            <strong> payment@jargalexpedition.com</strong>{" "}
                            <br /> In case you prefer other methods of payments
                            such Traveler Cheque or cash, please contact us at
                            <strong> info@jargalexpedition.com</strong> <br />
                            If you or anyone on your holiday booking decides to
                            cancel the holiday you must notify us of the
                            decision as soon as possible. Any notification must
                            be confirmed in writing or by e-mail within 24 hours
                            by the person who made the original booking.
                            Cancellation will take effect from the day we are
                            notified provided that written confirmation is
                            received by us within 24 hours of the original
                            notification. The following scale of charges will be
                            payable depending on when the notification of
                            cancellation is received. 30 days or more: deposit
                            forfeited;
                            <br />
                            29 – 15: 50% of total holiday cost
                            <br />
                            14 – 10: 65% of total holiday cost
                            <br />
                            9 – 5: 85% of total holiday cost
                            <br />
                            4 days or less: 100% of total holiday cost
                            <br />
                            You must take out travel insurance which should, in
                            most cases, include cover, under certain
                            circumstances, against loss of deposit or
                            cancellation fees.
                        </p>
                        <h3>3. YOUR HOLIDAY</h3>
                        <h3>3.1 HEALTH & SAFETY </h3>
                        <p>
                            Every effort is made to ensure your safety and well
                            being, but bookings are accepted on the
                            understanding that you appreciate the risks and
                            hazards associated with travel. If you or any member
                            have suffered from a disability or other medical
                            condition, please tell us before you book. Jargal
                            Expedition is happy to give you advice and to try to
                            assist you in choosing a holiday that will meet your
                            requirements. However, most of our holiday tours are
                            in destinations which are off the beaten track and
                            limited availability of facilities for disabled
                            guests such as ramps for wheelchairs, lifts and so
                            on. We take precautions to ensure that you are led
                            by highly qualified and experienced guides but you
                            must accept that, in purchasing these holidays, an
                            element of personal risk is involved. We pay special
                            attention to the safety of our guests. Mongolia is
                            generally safe place to travel in terms of health
                            and no specific vaccination are required. In order
                            to assist you, especially for horse riding, we must
                            be provided prior to booking with full written
                            details regarding your medical condition and any
                            special requirements which result from this.
                            Participants must comply with reasonable
                            instructions given by the organiser of the activity.{" "}
                        </p>
                        <h3>3.2 SPECIAL REQUESTS</h3>
                        <p>
                            Where special requests such as diet, room location
                            or twin or double bedded room are an important
                            factor in the choice of your holiday, you must
                            advise us before a booking is made.{" "}
                        </p>
                        <h3>3.3 PASSPORTS/VISA/HEALTH</h3>
                        <p>
                            Your passport valid for at least six months is
                            required by all nationals. Some nationals are also
                            required visas and you should clarify it or contact
                            the Embassy or Consulate of the country. All
                            children should travel on full passports. It is your
                            responsibility to ensure that you have all the
                            correct documentation for the holiday including
                            passports, visas, health certificates and
                            international driving licenses. We will not be
                            liable to make any refund or pay compensation if you
                            or any member of your party is unable to proceed
                            with the holiday as planned because of incorrect or
                            missing personal documents.
                        </p>
                        <h3>3.4 INSURANCE</h3>
                        <p>
                            All participants must be fully insured for the
                            duration of the tour. Participants are responsible
                            for arranging their own insurance which must cover
                            medical expenses, injury and cancellation. Customers
                            must provide the company with evidence of their
                            insurance. We recommend you take out insurance at
                            the time of booking to ensure it covers all
                            activities you are involved in and that you are
                            covered in case of tour and flight cancellations due
                            to bad weather, social unrest and terrorist acts or
                            any unforeseen circumstances beyond our control and
                            responsibilities.{" "}
                        </p>
                        <h3>3.5 PERSONAL ITEMS AND BAGGAGE </h3>
                        <p>
                            Personal items and baggage remain at all times the
                            responsibility of the participants.{" "}
                        </p>
                        <h3>3.6 GUIDE DECISIONS </h3>
                        <p>
                            Due to the adventurous nature of the tours, all
                            participants must at all times agree to comply with
                            the decisions taken by the guide. Therefore, for all
                            tours in the care of the guide or operator of your
                            trip you must comply with the instructions of that
                            person. It is a condition of your booking that you
                            accept that that person is entitled to require you
                            to dismount or to refuse to allow you to join if for
                            any reason, including your inability, behaviour or
                            health, they consider that you may endanger the
                            safety or welfare of any person, and if so required,
                            you have no claim and will not be entitled to any
                            refund or compensation. You also acknowledge that
                            all of the trips we arrange including horse riding
                            and other activities in areas that are remote and
                            difficult terrain or other conditions that can be
                            hazardous. Safety services and back-up operation may
                            also be more limited than usual. By booking to take
                            part in one of these trips, you confirm that you
                            understand and fully accept these risks.{" "}
                        </p>
                        <h3>4. COMMITMENT</h3>
                        <h3>4.1 OUR COMMITMENT TO YOU</h3>
                        <p>
                            Our liability to you we are responsible for ensuring
                            that your travel arrangements are supplied as agreed
                            before the booking. We take responsibility for the
                            services that we provide as well as the services of
                            our subcontractors. Exemptions are airlines
                            accidents or delays, loss of luggage, or medical and
                            customs regulation, for which we cannot take
                            responsibility. Our liability is limited to the
                            total cost of your travel arrangements. We are also
                            responsible for identifying any foreseeable risks
                            associated with your holiday. We will do what we can
                            to alert you and your companions to such risks and
                            take steps wherever possible to ameliorate against
                            them. If we change or cancel your holiday in the
                            unlikely case that we have to make changes to your
                            travel arrangements, we will notify you or your
                            travel agent at the earliest possible date. We do
                            reserve the right to make changes at any time due to
                            circumstances which lie beyond our control. In the
                            case of significant changes to your itinerary, you
                            have the right to cancel your holiday and be fully
                            refunded. If the changes increase the cost of your
                            holiday, we will notify you and invoice after your
                            acceptance of the difference in price. If the
                            changes decrease the cost of your holiday we will
                            also inform you and reimburse you the difference.
                            The effect of price increases the prices quoted on
                            our homepage are correct at the time of publication.
                            We reserve the right to change any of the prices,
                            services or other particulars contained on our
                            homepage at any time before we enter into a contract
                            with you. If there is any change, we will notify you
                            before we enter into such contract, and seek your
                            prior agreement to the changes.{" "}
                        </p>
                        <h3>4.2 YOUR COMMITMENT TO US </h3>
                        <p>
                            If you have chosen to travel with Jargal Expedition,
                            you must pay the deposit at the time of reservation
                            and must pay the outstanding balance at least 4
                            weeks prior to the departure date of your trip. If
                            you register within 4 weeks of departure, the full
                            cost should be paid at the time of registration. You
                            and your companions will need to be in suitable
                            physical condition to undertake the expedition as
                            set in your chosen itinerary and become fully aware
                            of the possible risks inherent in adventure travel.
                            You are responsible for paying for, or providing for
                            your own personal equipment, tips, airport taxes,
                            the cost of visas, vaccination, additional food and
                            drink, personal spending money, travel insurance,
                            and any other activities or provisions not included
                            in the itinerary. As previously mentioned, you must
                            ensure that your travel documents, full passport,
                            and visas are in order and will remain valid for the
                            entire length of your stay in Mongolia. Once we have
                            started to provide our service from the point of
                            your arrival in Mongolia, no refunds will be made
                            for unused trip arrangements for any reason. There
                            will be no refund given for unused hotel rooms,
                            meals, sightseeing, trip days or any other charges
                            once the trip has commenced. The cost is quoted as a
                            package price and credits are not given for services
                            not used that might arise as a result of loss,
                            damage, injury, delay or inconvenience.{" "}
                        </p>
                        <h3>4.3 COMPLAINTS </h3>
                        <p>
                            Should you have a complaint about the tour, contact
                            us immediately on our emergency number, Jargal
                            Expedition will try to make sure the complaint is
                            dealt with at destination. If you are unable to
                            contact us, your complaint must be made by letter
                            and received by Jargal Expedition within 14 days of
                            the end of the tour.
                        </p>
                    </div>
                </Container>
            </div>
        </>
    );
}
