import Head from "next/head";
import Path from "../components/Path";
import styles from "../styles/About.module.css";
import { Container, Form, FormGroup, Button, Row, Col } from "react-bootstrap";

export default function ForTravelAgent() {
    return (
        <>
            <Head>
                <title>For Travel Agent</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link
                    rel="canonical"
                    href="http://naadamfest.com/fortravelagent"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>

            <div>
                <Path name="About Us" />
                <Container>
                    <div className={styles.main}>
                        <h1>For Travel Agents </h1>
                        <p>
                            Jargal Expedition LLC is both very active and
                            attractive local tour operator responsible for
                            adventure holidays and horse riding engagements. It
                            is a fully licensed and locally operated Mongolian
                            tour operator company. We are happy to work with
                            travel agencies that actively promote our trips. In
                            order to qualify for a commission, please submit
                            your details below.{" "}
                        </p>
                        <Form style={{ marginInline: "50px" }}>
                            <Form.Group
                                as={Row}
                                className="mb-3"
                                controlId="formPlaintextEmail"
                            >
                                <Form.Label column sm="2">
                                    <h4>Agent name</h4>
                                </Form.Label>
                                <Col sm="8">
                                    <Form.Control type="text" />
                                </Col>
                            </Form.Group>
                            <Form.Group
                                as={Row}
                                className="mb-3"
                                controlId="formPlaintextEmail"
                            >
                                <Form.Label column sm="2">
                                    <h4>Address</h4>
                                </Form.Label>
                                <Col sm="8">
                                    <Form.Control type="text" />
                                </Col>
                            </Form.Group>
                            <Form.Group
                                as={Row}
                                className="mb-3"
                                controlId="formPlaintextEmail"
                            >
                                <Form.Label column sm="2">
                                    <h4>Country</h4>
                                </Form.Label>
                                <Col sm="8">
                                    <Form.Control type="text" />
                                </Col>
                            </Form.Group>
                            <Form.Group
                                as={Row}
                                className="mb-3"
                                controlId="formPlaintextPassword"
                            >
                                <Form.Label column sm="2">
                                    <h4> E-mail</h4>
                                </Form.Label>
                                <Col sm="8">
                                    <Form.Control type="text" />
                                </Col>
                            </Form.Group>
                        </Form>
                        <p>
                            We expect you to promote our trips actively with
                            your clients. Once you are registered with us, you
                            can earn commissions for all new reservations with
                            us. Jargal Expedition LLC.{" "}
                        </p>
                    </div>
                </Container>
            </div>
        </>
    );
}
