import { Container, Form, Button } from "react-bootstrap";
import { getRequestBrochure } from "../lib/api";
import Image from "next/image";
import styles from "../styles/SaveNow.module.scss";
import BlockContent from "@sanity/block-content-to-react";
import { useRef } from "react";
import emailjs from "emailjs-com";
import Head from "next/head";
import Path from "../components/Path";

export default function RequestBrochure({ data }) {
    const form = useRef();

    const sendMail = (e) => {
        e.preventDefault();
        emailjs
            .sendForm(
                "service_gxbg5jh",
                "template_fnnvxih",
                form.current,
                "user_NCFtk0eFn8gJVz7VICkwq"
            )
            .then(
                (result) => {
                    console.log("Email js send test", result.text);
                },
                (error) => {
                    console.log(error.text);
                }
            );
    };
    return (
        <>
            <Head>
                <title>Request Brochure</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link
                    rel="canonical"
                    href="http://naadamfest.com/requestbrochure"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>
            <Path name="Request Brochure" />

            <div style={{ marginBottom: "50px", position: "relative" }}>
                <Image
                    src={data[0]["image"]}
                    alt={data[0]["caption"]}
                    layout={"responsive"}
                    width={1350}
                    height={500}
                />
                <div className={styles.title3}>
                    <h1>{data[0]["caption"]}</h1>
                </div>
            </div>
            <Container>
                <div
                    style={{
                        fontSize: "2rem",
                        width: "100%",
                        fontFamily: "CenturySchool",
                    }}
                >
                    <BlockContent blocks={data[0]["text"]} />
                </div>
                <Form.Label>
                    Please provide the following information
                </Form.Label>
                <h5>Catalog Request</h5>
                <Form.Group className="mb-3 m-4" controlId="formBasicCheckbox">
                    <Form.Check
                        type="radio"
                        label="View digital catalog only"
                        name="formHorizontalRadios"
                        id="formHorizontalRadios1"
                    />
                    <Form.Check
                        type="radio"
                        label="Mail hard a copy to me"
                        name="formHorizontalRadios"
                        id="formHorizontalRadios2"
                    />
                </Form.Group>
                <Form method={"post"} onSubmit={sendMail} ref={form}>
                    <Form.Group className="mb-3" controlId="formBasicEmail">
                        <Form.Label>First name</Form.Label>
                        <Form.Control
                            type="text"
                            placeholder="first name"
                            name={"yourname"}
                        />
                    </Form.Group>

                    <Form.Group className="mb-3" controlId="formBasicPassword">
                        <Form.Label>Last name</Form.Label>
                        <Form.Control
                            type="text"
                            placeholder="last name"
                            name={"text"}
                        />
                    </Form.Group>
                    <Form.Group className="mb-3" controlId="formBasicPassword">
                        <Form.Label>Email</Form.Label>
                        <Form.Control
                            type="email"
                            placeholder="email"
                            name={"email"}
                        />
                    </Form.Group>

                    <Button
                        variant="outline-warning"
                        style={{
                            backgroundColor: "#ff6600",
                            color: "#fff",
                            marginBottom: "20px",
                        }}
                        type={"submit"}
                    >
                        Send
                    </Button>
                </Form>
            </Container>
        </>
    );
}

export const getServerSideProps = async () => {
    const data = await getRequestBrochure();
    return {
        props: {
            data,
        },
    };
};
