import { useState } from "react";
import { getSaveNow, getSaveNowTours } from "../lib/api";
import Image from "next/image";
import { Container, Button, Modal, Form } from "react-bootstrap";
import BlockContent from "@sanity/block-content-to-react";
import styles from "../styles/SaveNow.module.scss";
import { urlFor } from "../lib/api.js";
import Link from "next/link";
import MyModal from "../components/MyModal";
import Head from "next/head";

export default function SaveNow({ data, tourData }) {
    const ss = data[0];
    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);
    return (
        <>
            <Head>
                <title>Naadam festival</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link rel="canonical" href="http://naadamfest.com/savenow" />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>
            <div style={{ position: "relative" }}>
                <Image
                    src={ss.image}
                    alt={ss.caption}
                    layout={"responsive"}
                    width={1350}
                    height={525}
                />
                <div className={styles.title}>
                    <h1>{ss.caption}</h1>
                </div>
            </div>

            <Container>
                <div className={styles.block}>
                    <BlockContent blocks={ss.text} />
                </div>
                {tourData.map((tour, index) => (
                    <>
                        <div className={styles.card_main}>
                            <div
                                className={styles.card_image}
                                style={{
                                    backgroundImage: `url('${urlFor(tour.image)
                                        .auto("format")
                                        .fit("clip")
                                        .width(440)
                                        .quality(80)}`,
                                }}
                            />

                            <div className={styles.card_info}>
                                <p>Trip Style: Classic, Short Break</p>
                                <h1>{tour.title}</h1>
                                <p className={styles.price}>
                                    {tour["dateand"]["duration"]}
                                </p>
                                <hr style={{ color: "#ff6600" }} />
                                <div className={styles.sale_price}>
                                    <p className={styles.real_price}>
                                        ${tour["dateand"]["price"]}
                                    </p>
                                    <p style={{ color: "#ff6600" }}>
                                        ${tour["dateand"]["price"] * 0.75}
                                    </p>
                                </div>
                                <MyModal
                                    buttoName={"Request A Quote"}
                                    defTour={tour.title}
                                />
                            </div>
                        </div>
                    </>
                ))}
            </Container>
        </>
    );
}

export const getServerSideProps = async () => {
    const data = await getSaveNow();
    const tour = await getSaveNowTours();
    return {
        props: {
            data,
            tourData: tour,
        },
    };
};
