import Head from "next/head";
import Path from "../components/Path";
import styles from "../styles/WhyMongolia.module.css";
import { Container, Form, Button } from "react-bootstrap";
import { getTailorMadeHoliday } from "../lib/api";
import BlockContent from "@sanity/block-content-to-react";

export default function Tailor({ data }) {
    return (
        <>
            <Head>
                <title>Tailor Made Holiday</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link
                    rel="canonical"
                    href="http://naadamfest.com/tailormadeholiday"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>
            <div>
                <Path name="Tailor Made Holiday" />
            </div>

            <Container>
                <div className={styles.main}>
                    <div className={styles.main_title}>
                        <h1>{data[0]["title"]}</h1>
                        <p>{data[0]["subtitle"]}</p>
                    </div>
                    <div className={styles.content}>
                        <BlockContent
                            style={{
                                color: "#b8b8b8",
                                fontSize: "1.2rem",
                            }}
                            blocks={data[0]["block"]}
                        />
                    </div>
                    <div>
                        <div className={styles.main_title}>
                            <p style={{ textAlign: "left", fontWeight: "600" }}>
                                Contact us about Tailor Made Holiday
                            </p>
                        </div>
                    </div>
                </div>
                <div style={{ maxWidth: "700px", marginBottom: "50px" }}>
                    <Form>
                        <Form.Group className="mb-3" controlId="formBasicEmail">
                            <Form.Label>
                                <p style={{ color: "#1a4652" }}>Your Name</p>
                            </Form.Label>
                            <Form.Control
                                type="text"
                                placeholder="Enter your name"
                            />
                        </Form.Group>
                        <Form.Group
                            className="mb-3"
                            controlId="formBasicPassword"
                        >
                            <Form.Label>
                                <p style={{ color: "#1a4652" }}>Email</p>
                            </Form.Label>
                            <Form.Control
                                type="email"
                                placeholder="Enter email"
                            />
                        </Form.Group>
                        <Form.Group
                            className="mb-3"
                            controlId="formBasicPassword"
                        >
                            <Form.Label>
                                <p style={{ color: "#1a4652" }}>
                                    Your questions & comments
                                </p>
                            </Form.Label>
                            <Form.Control as="textarea" rows={3} />
                        </Form.Group>
                        <Button variant="primary" type="submit">
                            Send
                        </Button>
                    </Form>
                </div>
            </Container>
        </>
    );
}

export const getServerSideProps = async () => {
    const tailormadeholiday = await getTailorMadeHoliday();
    return {
        props: {
            data: tailormadeholiday,
        },
    };
};
