import Head from "next/head";
import Path from "../components/Path";
import styles from "../styles/About.module.css";
import { Container } from "react-bootstrap";
import { getTravelSupport } from "../lib/api";
import BlockContent from "@sanity/block-content-to-react";

export default function TravelSupport({ data }) {
    return (
        <>
            <Head>
                <title>Travel Support</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link
                    rel="canonical"
                    href="http://naadamfest.com/travelsupport"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>

            <div>
                <Path name="About Us" />
                <Container>
                    <div className={styles.main}>
                        {<BlockContent blocks={data[0]["desc"]} />}

                        {/*<h1>Mongolia Travel Information </h1>*/}
                        {/*<h3>Passports</h3>*/}
                        {/*<p>*/}
                        {/*    A full passport is required for all of our holidays*/}
                        {/*    and this should be valid for at least six months*/}
                        {/*    after the completion of your trip. To secure your*/}
                        {/*    booking and avoid incurring additional charges, you*/}
                        {/*    must provide information on your booking form*/}
                        {/*    precisely as it is shown on your passport. Passport*/}
                        {/*    and visa regulations can change at short notice, so*/}
                        {/*    you are advised to check current entry requirements*/}
                        {/*    with your embassy before you travel.*/}
                        {/*</p>*/}
                        {/*<h3>Visas</h3>*/}
                        {/*<p>*/}
                        {/*    You may require a visa to enter Mongolia. Your*/}
                        {/*    consultant will be happy to advise you on visa*/}
                        {/*    requirements.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Vaccinations</h3>*/}
                        {/*<p>*/}
                        {/*    For some countries you will undoubtedly require*/}
                        {/*    vaccinations for your visit. But Mongolia is*/}
                        {/*    generally safe place to travel in terms of health*/}
                        {/*    and no specific vaccination are required. You should*/}
                        {/*    consult a medical practitioner or travel clinic for*/}
                        {/*    specialist, up-to-date advice in advance of travel.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Health & Safety</h3>*/}
                        {/*<p>*/}
                        {/*    You should be prepared to take responsibility for*/}
                        {/*    your own safety on holiday. You need to follow local*/}
                        {/*    advice, listen to the advice of your guide and not*/}
                        {/*    take risks. It is imperative that you have*/}
                        {/*    comprehensive medical insurance for your holiday.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Population</h3>*/}
                        {/*<p>*/}
                        {/*    The current population is around 3.2 million. About*/}
                        {/*    96% of the population is Mongolians, along with*/}
                        {/*    smaller groups of other descent.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Capital and Government</h3>*/}
                        {/*<p>*/}
                        {/*    The capital is Ulaanbaatar, which has a population*/}
                        {/*    of almost 1,2 million. Mongolia is a parliamentary*/}
                        {/*    republic, officially called the Mongolia.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Payment Methods & Costs</h3>*/}
                        {/*<p>*/}
                        {/*    ATMs are available in major towns and larger*/}
                        {/*    villages and major credit cards such as Visa, Master*/}
                        {/*    Card and American Express are accepted at major*/}
                        {/*    shops and restaurants in UB. Shops in remote areas*/}
                        {/*    and fuel service stations may only accept cash.*/}
                        {/*    Traveller’s cheques are accepted at some banks but*/}
                        {/*    often with a high surcharge. There are banks at main*/}
                        {/*    airports, border posts and major towns. US Dollars,*/}
                        {/*    British Sterling and Euros are the most easily*/}
                        {/*    exchanged currencies.*/}
                        {/*</p>*/}
                        {/*<h3>Language & Religion</h3>*/}
                        {/*<p>*/}
                        {/*    Mongolian is the official language of Mongolia.*/}
                        {/*    English is taught in schools and spoken in urban*/}
                        {/*    areas. All guides and camp staff speak a good level*/}
                        {/*    of English. According to the latest census, 54% of*/}
                        {/*    the Mongolians identify as Buddhists, 39 % as not*/}
                        {/*    religious, 5 % as followers of the Mongol shamanic*/}
                        {/*    tradition, 4 % as Christians and 2% as Muslim*/}
                        {/*    (predominantly of Kazakh minority).*/}
                        {/*</p>*/}
                        {/*<h3>Area and Geography</h3>*/}
                        {/*<p>*/}
                        {/*    Mongolia is landlocked in the heart of Eurasia, the*/}
                        {/*    greatest terrestrial mass of the globe. It is the*/}
                        {/*    6th largest country in Asia and the 18th largest in*/}
                        {/*    the world occupying a territory of approximately 1.6*/}
                        {/*    million square kilometers, about the same surface*/}
                        {/*    area as France, Germany, Holland, Belgium, Spain and*/}
                        {/*    Portugal combined together. The terrain is one of*/}
                        {/*    mountains and rolling plateaus, with a high degree*/}
                        {/*    of relief.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Climate</h3>*/}
                        {/*<p>*/}
                        {/*    Mongolia&apos;s climate can be described has highly*/}
                        {/*    continental dominated climate with warm summers and*/}
                        {/*    long, dry and very cold winters. Known as the land*/}
                        {/*    of blue sky&apos;, Mongolia is a very sunny country*/}
                        {/*    and has usually about 250 sunny days a year. The*/}
                        {/*    country has the world&apos;s most typical*/}
                        {/*    continental climate with extreme diurnal and annual*/}
                        {/*    ranges of temperature. Average temperature in most*/}
                        {/*    of the country is below zero from November to March.*/}
                        {/*    d*/}
                        {/*</p>*/}
                        {/*<h3>Communications</h3>*/}
                        {/*<p>*/}
                        {/*    The international telephone code is +976, so you*/}
                        {/*    dial 00 976 from the outside Mongolia. To make an*/}
                        {/*    international call when in Mongolia you dial 00 plus*/}
                        {/*    the country code. Roaming agreements exist with*/}
                        {/*    international mobile phone companies. Coverage is*/}
                        {/*    mainly limited to the main inhabited areas. Internet*/}
                        {/*    is available in large towns and tourist centres.*/}
                        {/*</p>*/}
                        {/*<h3>Food & Drink</h3>*/}
                        {/*<p>*/}
                        {/*    Restaurants and bars can be found in most towns.*/}
                        {/*    Although Mongolia is not really known for its*/}
                        {/*    cuisine, the standard of food in lodges and camps*/}
                        {/*    tends to be of a very high standard. Beef and lamb*/}
                        {/*    are the most popular meats, though chicken and pork*/}
                        {/*    are also widely available. Most camps and lodges*/}
                        {/*    stock a selection of wines to be enjoyed with meals.{" "}*/}
                        {/*</p>*/}
                        {/*<h3>Shopping</h3>*/}
                        {/*<p>*/}
                        {/*    All major towns have shopping centres and*/}
                        {/*    supermarkets stocking basic commodities. There are*/}
                        {/*    also 24-hour convenience shops at most fuel service*/}
                        {/*    stations. Favourite purchases include Mongolian*/}
                        {/*    famous cashmere and antique.{" "}*/}
                        {/*</p>*/}
                    </div>
                </Container>
            </div>
        </>
    );
}

export const getStaticProps = async () => {
    const data = await getTravelSupport();
    return {
        props: {
            data,
        },
    };
};
