import Head from "next/head";
import Path from "../components/Path";
import styles from "../styles/WhyMongolia.module.css";
import { Container } from "react-bootstrap";
import Image from "next/image";
import { getWhyMongolia } from "../lib/api";

function Content({ title, text, image }) {
    return (
        <>
            <Head>
                <title>Why Mongolia</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="description" content="Naadam festival event" />
                <meta name="author" content="Naadam Festival" />
                <meta
                    name="keywords"
                    content="Naadam festival, Tailor Made Mongolia, Mongolia, Mongol naadam, NAADAM FESTIVAL AND ANCIENT CAPITAL CITY, NAADAM FESTIVAL AND CENTRAL REGION OF MONGOLIA,
                    NAADAM FESTIVAL AND EPIC MONGOLIAN OVERLAND, NAADAM FESTIVAL AND GREAT GOBI DESERT, NAADAM FESTIVAL AND MONGOLIAN BLUE PEARL, NAADAM FESTIVAL AND ULTIMATE WEST,
                    Jargal Expedition, Mongolia Travel Information, tailor made holidays in Mongolia"
                />
                <meta property="og:type" content="website" />
                {/*End url bichne*/}
                <meta property="og:url" content="http://naadamfest.com/" />
                <meta
                    property="og:title"
                    content="naadamfest.com :: Naadam Festival"
                />
                <meta
                    property="og:description"
                    content="For millennia, herders have lived on the Mongolian land, living as free as the country is wide. Mongolia’s vast steppe is home to one of the world’s last surviving nomadic cultures. The Mongolian steppe remains mostly intact, and its nomadic way of life has been largely unchanged for generations. Some herding customs alive today pre-date the era of Genghis Khan."
                />
                <meta property="og:site_name" content="naadamfest.com" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="799" />
                <meta
                    property="og:image"
                    content="http://naadamfest.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Faj69bwet%2Fproduction%2F87731def5a651b9d29f99489ab9cd3077cebed78-3215x960.png&w=1920&q=75"
                />
                <meta property="og:locale" content="en_US" />
                <meta property="og:site_name" content="naadamfest.com" />
                <link
                    rel="canonical"
                    href="http://naadamfest.com/whymongolia"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>
            <div className={styles.content}>
                <div className={styles.title}>{title}</div>
                <div className={styles.image_text}>
                    <div>
                        <Image
                            src={image}
                            alt="naadam festival"
                            width={400}
                            height={250}
                            layout="fixed"
                            objectFit="cover"
                            quality={90}
                        />
                    </div>
                    <div className={styles.con_text}>
                        <p>{text}</p>
                    </div>
                </div>
            </div>
        </>
    );
}

export default function WhyMongolia({ data }) {
    return (
        <>
            <Head>
                <title>Why Mongolia</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon_n.ico" />
            </Head>
            <div>
                <Path name="Why Mongolia" />
            </div>
            <Container>
                <div className={styles.main}>
                    <div className={styles.main_title}>
                        <h1>Why Mongolia</h1>
                        <p>Mongolia&apos;s Top Highlights</p>
                    </div>
                </div>
                <div>
                    {data.map((d, index) => (
                        <Content
                            key={index}
                            title={d.title}
                            text={d.desc}
                            image={d.image}
                        />
                    ))}
                </div>
            </Container>
        </>
    );
}
export const getServerSideProps = async () => {
    const data = await getWhyMongolia();
    return {
        props: {
            data,
        },
    };
};
